# Generated by Django 4.2.30 on 2026-08-23 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('projects', '0002_projectimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('report_date', models.DateField()),
                ('weather_condition', models.CharField(blank=True, max_length=100)),
                ('weather_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weather_min_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weather_max_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weather_rainfall', models.DecimalField(blank=True, decimal_places=2, help_text='Rainfall in millimetres', max_digits=6, null=True)),
                ('weather_comment', models.TextField(blank=True)),
                ('work_start_time', models.TimeField(blank=True, null=True)),
                ('work_end_time', models.TimeField(blank=True, null=True)),
                ('workers_count', models.PositiveIntegerField(blank=True, null=True)),
                ('workers_comment', models.TextField(blank=True)),
                ('contractors_count', models.PositiveIntegerField(blank=True, null=True)),
                ('contractors_comment', models.TextField(blank=True)),
                ('visitors_count', models.PositiveIntegerField(blank=True, null=True)),
                ('visitors_comment', models.TextField(blank=True)),
                ('deliveries_count', models.PositiveIntegerField(blank=True, null=True)),
                ('deliveries_comment', models.TextField(blank=True, default='No deliveries recorded.')),
                ('work_completed', models.TextField(blank=True)),
                ('delays', models.TextField(blank=True, default='No delays reported.')),
                ('planned_work', models.TextField(blank=True, default='No tasks planned for tomorrow.')),
                ('incidents', models.TextField(blank=True, default='No incidents reported.')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('toolbox_talk_held', models.BooleanField(default=False)),
                ('toolbox_talk_topic', models.CharField(blank=True, max_length=200)),
                ('safety_issues', models.TextField(blank=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports_created', to='authentication.usermodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='projects.projectmodel')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyreportmodel',
            constraint=models.UniqueConstraint(fields=('project', 'report_date'), name='unique_daily_report_per_project'),
        ),
    ]
