# Generated by Django 4.2.30 on 2026-08-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportmodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
