# Generated by Django 4.2.30 on 2026-08-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_dailyreportmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportmodel',
            name='weather_humidity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Relative humidity (%)', null=True),
        ),
        migrations.AddField(
            model_name='dailyreportmodel',
            name='weather_rain_probability',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum probability of rain (%)', null=True),
        ),
        migrations.AddField(
            model_name='dailyreportmodel',
            name='weather_wind_speed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wind speed in km/h', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreportmodel',
            name='weather_max_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum temperature in °C', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreportmodel',
            name='weather_min_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum temperature in °C', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreportmodel',
            name='weather_rainfall',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected/recorded precipitation in millimetres', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreportmodel',
            name='weather_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current temperature in °C', max_digits=5, null=True),
        ),
    ]
