# Generated by Django 4.2.30 on 2026-08-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_dailyreportmodel_weather_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportmodel',
            name='toolbox_attendees_count',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
