# Generated by Django 4.2.30 on 2026-08-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_dailyreportmodel_toolbox_attendees_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportmodel',
            name='toolbox_talk_held',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
