# Generated by Django 4.2.30 on 2026-08-26 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('report', '0005_alter_dailyreportmodel_toolbox_talk_held'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportmodel',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports_completed_by', to='authentication.usermodel'),
        ),
    ]
