# Generated by Django 4.2.30 on 2026-09-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_dailyreportmodel_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportmodel',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
