# Generated by Django 4.2.30 on 2026-09-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_dailyreportmodel_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreportmodel',
            old_name='submitted_at',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='dailyreportmodel',
            name='deliveries_comment',
        ),
        migrations.RemoveField(
            model_name='dailyreportmodel',
            name='deliveries_count',
        ),
        migrations.RemoveField(
            model_name='dailyreportmodel',
            name='incidents',
        ),
        migrations.RemoveField(
            model_name='dailyreportmodel',
            name='planned_work',
        ),
        migrations.AddField(
            model_name='dailyreportmodel',
            name='foreman',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportmodel',
            name='superintendent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
