# Generated by Django 4.2.30 on 2026-09-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_rename_submitted_at_dailyreportmodel_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportmodel',
            name='contractors_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreportmodel',
            name='visitors_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreportmodel',
            name='workers_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
