# Generated by Django 4.2.30 on 2026-09-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_dailyreportmodel_contractors_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportmodel',
            name='toolbox_attendees_count',
            field=models.CharField(blank=True, default='0', max_length=200),
        ),
    ]
