# Generated by Django 4.2.30 on 2026-09-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_alter_dailyreportmodel_toolbox_attendees_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportmodel',
            name='toolbox_attendees_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
