# Generated by Django 4.2.30 on 2026-08-25 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractorrelation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_contractor', to='authentication.usermodel'),
        ),
    ]
