# Generated by Django 4.2.30 on 2026-08-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
