# Generated by Django 4.2.30 on 2026-09-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issuemodel_daily_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecommentmodel',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
