# Generated by Django 4.2.30 on 2026-09-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('issues', '0004_issuecommentmodel_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuemodel',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_by', to='authentication.usermodel'),
        ),
    ]
