# Generated by Django 4.2.30 on 2026-08-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentmodel',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_incident', to='authentication.usermodel'),
        ),
        migrations.AlterField(
            model_name='incidentmodel',
            name='incident_type',
            field=models.CharField(choices=[('near Miss', 'Near Miss'), ('first Aid', 'First Aid '), ('medical Treatment', 'Medical Treatment'), ('lost Time Injury', 'Lost Time Injury '), ('property Damage', 'Property Damage'), ('environmental Incident', 'Environmental Incident '), ('Vehicle Accident', 'Medical Treatment')], max_length=100),
        ),
    ]
