# Generated by Django 4.2.30 on 2026-08-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incidentmodel_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentmodel',
            name='injuries',
            field=models.TextField(blank=True),
        ),
    ]
