# Generated by Django 4.2.30 on 2026-08-28 09:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incidentmodel_injuries'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentmodel',
            name='work',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='WitnessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('contract', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witness', to='incidents.incidentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='InjuredPersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('injury', models.CharField(blank=True, max_length=255)),
                ('body_part', models.CharField(blank=True, max_length=255)),
                ('treatment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='injured_person', to='incidents.incidentmodel')),
            ],
        ),
    ]
