# Generated by Django 4.2.30 on 2026-08-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('incidents', '0004_incidentmodel_work_witnessmodel_injuredpersonmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to='authentication.usermodel'),
        ),
    ]
