# Generated by Django 4.2.30 on 2026-09-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_alter_incidentmodel_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentmodel',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentmodel',
            name='injuries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentmodel',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20, null=True),
        ),
    ]
