# Generated by Django 4.2.30 on 2026-08-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionquestionmodel',
            name='not_applicable',
            field=models.ManyToManyField(blank=True, default=None, related_name='na_question', to='projects.projectmodel'),
        ),
    ]
