# Generated by Django 4.2.30 on 2026-08-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('inspections', '0002_inspectionquestionmodel_not_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectioncategorymodel',
            name='not_applicable',
            field=models.ManyToManyField(blank=True, default=None, related_name='na_category', to='projects.projectmodel'),
        ),
    ]
