# Generated by Django 4.2.30 on 2026-08-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_inspectioncategorymodel_not_applicable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('incomplete', 'incomplete'), ('completed', 'Completed'), ('ready', 'Ready'), ('overdue', 'Overdue'), ('in_progress', 'In Progress'), ('draft', 'Draft')], default='pending', max_length=20),
        ),
    ]
