# Generated by Django 4.2.30 on 2026-09-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_alter_inspectionmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionmodel',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
