# Generated by Django 4.2.30 on 2026-08-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_dailyreportmodel_status'),
        ('projects', '0002_projectimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimages',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_photo', to='report.dailyreportmodel'),
        ),
    ]
