# Generated by Django 4.2.30 on 2026-08-24 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_deliverymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimages',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_files', to='projects.deliverymodel'),
        ),
    ]
