# Generated by Django 4.2.30 on 2026-08-24 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incidentmodel_assigned_to_and_more'),
        ('projects', '0005_projectimages_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimages',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_files', to='incidents.incidentmodel'),
        ),
    ]
