# Generated by Django 4.2.30 on 2026-08-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectimages_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimages',
            name='reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
