# Generated by Django 4.2.30 on 2026-08-25 13:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('authentication', '0001_initial'),
        ('projects', '0007_projectimages_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activity_type', models.CharField(blank=True, choices=[('Project Created', 'Project Created'), ('Project Updated', 'Project Updated'), ('Inspection Started', 'Inspection Started'), ('Inspection Completed', 'Inspection Completed'), ('Issue Created', 'Issue Created'), ('Issue Assigned', 'Issue Assigned'), ('Issue Updated', 'Issue Updated'), ('Issue Resolved', 'Issue Resolved'), ('Task Created', 'Task Created'), ('Task Assigned', 'Task Assigned'), ('Task Completed', 'Task Completed'), ('Daily Report Created', 'Daily Report Created'), ('Daily Report Submitted', 'Daily Report Submitted'), ('Photo Uploaded', 'Photo Uploaded'), ('User Added', 'User Added')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='account.companyprofilemodel')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.projectmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='authentication.usermodel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='projects_ac_project_85d00b_idx'), models.Index(fields=['company', '-created_at'], name='projects_ac_company_2fdc6a_idx'), models.Index(fields=['user', '-created_at'], name='projects_ac_user_id_17a435_idx'), models.Index(fields=['activity_type'], name='projects_ac_activit_0b66b7_idx')],
            },
        ),
    ]
