# Generated by Django 4.2.30 on 2026-08-28 11:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectcontractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10000)),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_item', to='projects.deliverymodel')),
            ],
        ),
    ]
