# Generated by Django 4.2.30 on 2026-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_delivereditemsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodel',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverymodel',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
