# Generated by Django 4.2.30 on 2026-08-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_deliverymodel_delivery_time_deliverymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodel',
            name='reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
