# Generated by Django 4.2.30 on 2026-08-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_deliverymodel_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymodel',
            name='type',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
