# Generated by Django 4.2.30 on 2026-08-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_activitymodel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitymodel',
            old_name='type',
            new_name='icon_type',
        ),
    ]
