# Generated by Django 4.2.30 on 2026-08-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_rename_type_activitymodel_icon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymodel',
            name='status',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
