# Generated by Django 4.2.30 on 2026-09-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_deliverymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/'),
        ),
    ]
