# Generated by Django 4.2.30 on 2026-09-12 14:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_projectimages_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFilesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='project_photos/')),
                ('file', models.FileField(blank=True, null=True, upload_to='project_files/')),
                ('caption', models.TextField(blank=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_attachments', to='projects.deliverymodel')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_files', to='projects.projectmodel')),
            ],
        ),
    ]
