# Generated by Django 4.2.30 on 2026-09-12 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('projects', '0017_projectfilesupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfilesupload',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploader', to='authentication.usermodel'),
        ),
    ]
