# Generated by Django 4.2.30 on 2026-09-12 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('projects', '0018_projectfilesupload_uploaded_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfilesupload',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projectfilesupload',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, default=projects.models.default_uploaded_by_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_files', to='authentication.usermodel'),
        ),
    ]
