# Generated by Django 4.2.30 on 2026-09-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_dailyreportmodel_reference'),
        ('projects', '0020_projectuploadedfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuploadedfiles',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_attachments', to='report.dailyreportmodel'),
        ),
    ]
