# Generated by Django 4.2.30 on 2026-09-12 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issuemodel_daily_report'),
        ('projects', '0021_projectuploadedfiles_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuploadedfiles',
            name='issue_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_task_attachments', to='issues.issuemodel'),
        ),
    ]
