# Generated by Django 4.2.30 on 2026-09-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issuecommentmodel_is_read'),
        ('projects', '0022_projectuploadedfiles_issue_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuploadedfiles',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_attachments', to='issues.issuecommentmodel'),
        ),
    ]
